// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple riscv64 -target-feature +xinchivdemo -emit-llvm %s -o - \
// RUN:     -disable-O0-optnone | opt -S -passes=mem2reg \
// RUN:     | FileCheck %s  -check-prefix=RV64XINCHIVDEMO

#include <riscv_inchi.h>


// RV64XINCHIVDEMO-LABEL: @testcp32(
// RV64XINCHIVDEMO-NEXT:  entry:
// RV64XINCHIVDEMO-NEXT:    [[TMP0:%.*]] = ptrtoint ptr [[RS1:%.*]] to i64
// RV64XINCHIVDEMO-NEXT:    [[TMP1:%.*]] = ptrtoint ptr [[RS2:%.*]] to i64
// RV64XINCHIVDEMO-NEXT:    [[TMP2:%.*]] = call i64 @llvm.riscv.inchi.cp32(i64 [[TMP0]], i64 [[TMP1]])
// RV64XINCHIVDEMO-NEXT:    [[TMP3:%.*]] = inttoptr i64 [[TMP2]] to ptr
// RV64XINCHIVDEMO-NEXT:    ret ptr [[TMP3]]
//
uint64_t* testcp32(uint64_t* rs1, uint64_t* rs2) {
  return __riscv_inchi_cp32(rs1, rs2);
}

// RV64XINCHIVDEMO-LABEL: @testmadd32(
// RV64XINCHIVDEMO-NEXT:  entry:
// RV64XINCHIVDEMO-NEXT:    [[TMP0:%.*]] = call i64 @llvm.riscv.inchi.madd32(i64 [[RS1:%.*]], i64 [[RS2:%.*]], i64 [[RS3:%.*]])
// RV64XINCHIVDEMO-NEXT:    ret i64 [[TMP0]]
//
uint64_t testmadd32(uint64_t rs1, uint64_t rs2, uint64_t rs3) {
  return __riscv_inchi_madd32(rs1, rs2, rs3);
}
