; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv64 -mattr=+xinchivdemo -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=RV64XINCHIVDEMO

declare i64 @llvm.riscv.inchi.cp32(i64, i64);

define i64 @cp32(i64 %a, i64 %b) nounwind {
; RV64XINCHIVDEMO-LABEL: cp32:
; RV64XINCHIVDEMO:       # %bb.0:
; RV64XINCHIVDEMO-NEXT:    inchi.cp32 a0, a0, a1
; RV64XINCHIVDEMO-NEXT:    ret
    %val = call i64 @llvm.riscv.inchi.cp32(i64 %a, i64 %b)
    ret i64 %val
}

declare i64 @llvm.riscv.inchi.madd32(i64, i64, i64);

define i64 @madd32(i64 %a, i64 %b, i64 %c) nounwind {
; RV64XINCHIVDEMO-LABEL: madd32:
; RV64XINCHIVDEMO:       # %bb.0:
; RV64XINCHIVDEMO-NEXT:    inchi.madd32 a0, a1, a2
; RV64XINCHIVDEMO-NEXT:    ret
    %val = call i64 @llvm.riscv.inchi.madd32(i64 %a, i64 %b, i64 %c)
    ret i64 %val
}
